### ISSUE TITLE
Thanks for being the reason I can't use my name to sign up online.

### ISSUE THREAD

**Issue by lucoot** [snipe/banbuilder-library#111]
Please include a warning about the [Scunthrope Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem#:~:text=The%20Scunthorpe%20problem%20is%20the,obscene%20or%20otherwise%20unacceptable%20meaning.) So that users of this list and similar lists don't discriminate against people with "profanity" in their names.

**Comment by snipe** [comment]
Hi @lucoot - I read your email, and I feel for you. 

I do actually address this directly on the website. http://banbuilder.com 

<img width="661" alt="Screenshot 2023-10-04 at 11 11 32 AM" src="https://github.com/snipe/banbuilder/assets/197404/e72a9686-ec31-4028-9910-9ff39757dc1c">

Your last name is certainly one of the less offensive words in our default list, but that's why we allow the devs to create their own lists. We strongly encourage people to build their own lists (especially as it relates to their own languages) for specifically this reason. As someone learning European Portuguese, there are utterly harmless words ("girl") I could say here but if I go to Brazil (where they also speak Portuguese), I'll get myself into a bad situation. 

I'm genuinely sorry. I had an unusual last name growing up and the kids on the playground were merciless. 

I tried to make a library that gave devs enough basic coverage for Disney-rated chat, legal compliance, etc - but at the end of the day, it's up to each dev (and each legal department) to customize the lists as needed.


<blockquote><div><strong><a href="http://banbuilder.com/">BanBuilder - PHP profanity filter composer package for application developers, moderators, etc.</a></strong></div><div>Banbuilder : Because its about $&@%#$@$ time!</div></blockquote>
